netCorePiesFromScratch/Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;
using netCorePiesFromScratch.Models;

namespace netCorePiesFromScratch.Controllers
{
    public class FeedbackController : Controller
    {

        private readonly IFeedbackRepository _feedbackRepository;

        public FeedbackController(IFeedbackRepository feedbackRepository)
        {
            _feedbackRepository = feedbackRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                _feedbackRepository.AddFeedBack(feedback);
                return RedirectToAction("FeedbackComplete");
            }

            return View(feedback);
        }

        public IActionResult FeedbackComplete()
        {
            return View();
        }
    }
}

netCorePiesFromScratch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/content/site.css" />
    <title>Pie Shop</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Pie shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a asp-controller="Home" asp-action="Index" class="nav-item nav-link">Pie shop</a>
                <a asp-controller="Feedback" asp-action="Index" class="nav-item nav-link">Send feedback</a>
            </div>
        </div>
    </div>
</nav>
<div class="container body-content">
    <div class="row">
        @RenderBody()
    </div>
</div>
@RenderSection("Scripts", required: false)
</body>

</html>